export const USER_LOGIN = 'user/Login'
export const USER_REGISTER = 'user/Register'
export const GET_MOVIE = 'movie/GetMovie'
export const GET_GENRE = 'genre/GetGenre'
export const GET_MOVIE_BY_ID = 'movie/GetMovieById'
export const DELETE_MOVIE = 'movie/DeleteMovie'
export const ADD_GENRE = 'genre/AddGenre'
export const DELETE_GENRE = 'genre/DeleteGenre'